export const GET_INGR='GET_INGR';
export const ADD_INGR='ADD_INGR';
export const REMOVE_INGR='REMOVE_INGR';
export const ERROR='ERROR';

export const SUBMIT_SUCCESSFUL='SUBMIT_SUCCESSFUL';
export const SUBMIT_FAILED='SUBMIT_FAILED';
export const SUBMIT_ORDER='SUBMIT_ORDER';
export const INIT_PURCHASE='INIT_PURCHASE';

export const FETCH_ORDER='FETCH_ORDER';
export const FETCH_ORDER_SUCCESS='FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILED='FETCH_ORDER_FAILED';

export const AUTH_START ='AUTH_START';
export const AUTH_SUCCESS ='AUTH_SUCCESS';
export const AUTH_FAILED ='AUTH_FAILED';
